import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import Link from "next/link";

export const metadata = { title: "Terms & Conditions | IIA Telangana Chapter" };

const section: React.CSSProperties = { marginBottom: "2rem" };
const h2Style: React.CSSProperties = { fontSize: "1.05rem", fontWeight: 700, color: "#c9a227", marginBottom: "0.6rem", marginTop: "1.5rem" };
const p: React.CSSProperties = { fontSize: "0.92rem", lineHeight: 1.85, color: "rgba(240,237,230,0.75)", margin: "0 0 0.75rem" };
const li: React.CSSProperties = { fontSize: "0.92rem", lineHeight: 1.85, color: "rgba(240,237,230,0.75)", marginBottom: "0.75rem" };

export default function TermsPage() {
  return (
    <div style={{ background: "#0f2060", minHeight: "100vh", color: "#f0ede6" }}>
      <Navbar />
      <main style={{ maxWidth: 820, margin: "0 auto", padding: "8rem 1.75rem 5rem" }}>
        <div style={{ marginBottom: "3rem", borderBottom: "1px solid rgba(201,162,39,0.2)", paddingBottom: "2rem" }}>
          <p style={{ fontSize: "0.7rem", letterSpacing: "0.25em", textTransform: "uppercase", color: "#c9a227", marginBottom: "0.75rem" }}>Legal</p>
          <h1 style={{ fontFamily: "var(--font-playfair,Georgia,serif)", fontSize: "clamp(1.8rem,4vw,2.8rem)", fontWeight: 700, margin: 0 }}>Terms &amp; Conditions</h1>
          <p style={{ ...p, marginTop: "1rem", marginBottom: 0 }}>Last updated: June 2026</p>
        </div>

        <div style={section}>
          <p style={p}>This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.</p>
          <p style={p}>This document is published in accordance with the provisions of Rule 3(1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of domain name <strong style={{ color: "#c9a227" }}>https://iiatchapter.netlify.app</strong> ('Website'), including the related mobile site and mobile application (hereinafter referred to as 'Platform').</p>
          <p style={p}>The Platform is owned by <strong style={{ color: "#f0ede6" }}>THE INDIAN INSTITUTE OF ARCHITECTS, TELANGANA CHAPTER</strong>, with its registered office at <strong style={{ color: "#f0ede6" }}>802C Al Karim Trade Centre, MG Road, Ranigunj, Secunderabad, Telangana 500003</strong> (hereinafter referred to as 'Platform Owner', 'we', 'us', 'our').</p>
          <p style={p}>Your use of the Platform and services and tools are governed by the following terms and conditions ("Terms of Use") as applicable to the Platform including the applicable policies which are incorporated herein by way of reference. If You transact on the Platform, You shall be subject to the policies that are applicable to the Platform for such transaction. By mere use of the Platform, You shall be contracting with the Platform Owner and these terms and conditions including the policies constitute Your binding obligations with Platform Owner.</p>
          <p style={{ ...p, fontWeight: 600, color: "#f0ede6", textTransform: "uppercase", fontSize: "0.85rem", letterSpacing: "0.03em" }}>ACCESSING, BROWSING OR OTHERWISE USING THE PLATFORM INDICATES YOUR AGREEMENT TO ALL THE TERMS AND CONDITIONS UNDER THESE TERMS OF USE, SO PLEASE READ THE TERMS OF USE CAREFULLY BEFORE PROCEEDING.</p>
        </div>

        <div style={section}>
          <h2 style={h2Style}>Terms of Use</h2>
          <p style={p}>The use of Platform and/or availing of our Services is subject to the following Terms of Use:</p>
          <ol style={{ paddingLeft: "1.25rem", margin: 0 }}>
            {[
              "To access and use the Services, you agree to provide true, accurate and complete information to us during and after registration, and you shall be responsible for all acts done through the use of your registered account on the Platform.",
              "Neither we nor any third parties provide any warranty or guarantee as to the accuracy, timeliness, performance, completeness or suitability of the information and materials offered on this website or through the Services, for any specific purpose. You acknowledge that such information and materials may contain inaccuracies or errors and we expressly exclude liability for any such inaccuracies or errors to the fullest extent permitted by law.",
              "Your use of our Services and the Platform is solely and entirely at your own risk and discretion for which we shall not be liable to you in any manner. You are required to independently assess and ensure that the Services meet your requirements.",
              "The contents of the Platform and the Services are proprietary to us and are licensed to us. You will not have any authority to claim any intellectual property rights, title, or interest in its contents. The contents includes and is not limited to the design, layout, look and graphics.",
              "You acknowledge that unauthorized use of the Platform and/or the Services may lead to action against you as per these Terms of Use and/or applicable laws.",
              "You agree to pay us the charges associated with availing the Services.",
              "You agree not to use the Platform and/or Services for any purpose that is unlawful, illegal or forbidden by these Terms, or Indian or local laws that might apply to you.",
              "You agree and acknowledge that website and the Services may contain links to other third party websites. On accessing these links, you will be governed by the terms of use, privacy policy and such other policies of such third party websites.",
              "You understand that upon initiating a transaction for availing the Services you are entering into a legally binding and enforceable contract with the Platform Owner for the Services.",
              "You shall indemnify and hold harmless Platform Owner, its affiliates, group companies (as applicable) and their respective officers, directors, agents, and employees, from any claim or demand, or actions including reasonable attorney's fees, made by any third party or penalty imposed due to or arising out of Your breach of this Terms of Use, privacy Policy and other Policies, or Your violation of any law, rules or regulations or the rights (including infringement of intellectual property rights) of a third party.",
              "Notwithstanding anything contained in these Terms of Use, the parties shall not be liable for any failure to perform an obligation under these Terms if performance is prevented or delayed by a force majeure event.",
              "These Terms and any dispute or claim relating to it, or its enforceability, shall be governed by and construed in accordance with the laws of India.",
              "All disputes arising out of or in connection with these Terms shall be subject to the exclusive jurisdiction of the courts in Hyderabad, Telangana, India.",
              "All concerns or communications relating to these Terms must be communicated to us using the contact information provided on this website.",
            ].map((text, i) => (
              <li key={i} style={li}>{text}</li>
            ))}
          </ol>
        </div>

        <div style={{ borderTop: "1px solid rgba(201,162,39,0.15)", paddingTop: "2rem", display: "flex", gap: "1.5rem", flexWrap: "wrap" }}>
          <Link href="/privacy" style={{ fontSize: "0.85rem", color: "#c9a227", textDecoration: "none" }}>Privacy Policy →</Link>
          <Link href="/refund" style={{ fontSize: "0.85rem", color: "#c9a227", textDecoration: "none" }}>Refund Policy →</Link>
          <Link href="/" style={{ fontSize: "0.85rem", color: "rgba(240,237,230,0.5)", textDecoration: "none" }}>← Back to Home</Link>
        </div>
      </main>
      <Footer />
    </div>
  );
}
